import countryJson from "./countryJson.json"
export type TranslationObject = { [localCountryName: string]: string }

interface CountryKeyValue {
    key: string;
    values: string[];
}

const countryNames: CountryKeyValue[] = [
    {
        key: "Italy",
        values: [
            "Itálie",
            "Italia",
        ],
    },
];

const prepareImportMap = (): Map<string, string> => {
    const result = new Map<string, string>();
    for (const country of countryNames) {
        for (const value of country.values) {
            result.set(value, country.key);
        }
    }
    return result;
};
const prepareImportMapFromJson = (): Map<string, string> => {
    const result = new Map<string, string>();
    for (const country of Object.keys(countryJson)) {
        // TODO
        /*for (const value of country.values) {
            result.set(value, country.key);
        }*/
    }
    return result;
};

export const CountryTranslation: TranslationObject = {
    "Itálie": "Italy",
    "Italia": "Italy",
    "Slovensko": "Slovakia",
    "Rakousko": "Austria",
    "Österreich": "Austria",
    "Kanada": "Canada",
    "Polsko": "Poland",
    "Polska": "Poland",
    "Belgie": "Belgium",
    "Írán": "Iran",
    "Nizozemsko": "Netherlands",
    "Nederland": "Netherlands",
    "Německo": "Germany",
    "Deutschland": "Germany",
    "Brazílie": "Brasil",
    "România": "Romania",
    "Rumunsko": "Romania",
    "Turecko": "Turkey",
    "Türkiye": "Turkey",
    "Kazachstán": "Kazakhstan",
    "Bulharsko": "Bulgaria",
    "Švédsko": "Sweden",
    "Sverige": "Sweden",
    "Portugalsko": "Portugal",
    "Hrvatska": "Croatia",
    "Chorvatsko": "Croatia",
    "Čínská lidová republika": "China",
    "People's Republic of China": "China",
    "Singapur": "Singapore",
    "Švýcarsko": "Switzerland",
    "Schweiz": "Switzerland",
    "Česká republika": "Czech Republic",
    "Filipíny": "Philippines",
    "Pilipinas": "Philippines",
    "Anglie": "England",
    "Bělorusko": "Belarus",
    "Španělsko": "Spain",
    "España": "Spain",
    "Jamajka": "Jamaica",
    "Izrael": "Israel",
    "Francie": "France",
    "Maďarsko": "Hungary",
    "Magyarország": "Hungary",
    "Nigérie": "Nigeria",
    "Kapverdy": "Cape Verde",
    "Cabo Verde": "Cape Verde",
    "Skotsko": "Scotland",
    "Lucembursko": "Luxembourg",
    "Lëtzebuerg": "Luxembourg",
    "Bosna a Hercegovina": "Bosnia and Herzegovina",
    "Bosna i Hercegovina": "Bosnia and Herzegovina",
    "Dánsko": "Denmark",
    "Danmark": "Denmark",
    "Rusko": "Russia",
    "Rossiya": "Russia",
    "Kamerun": "Cameroon",
    "Perú": "Peru",
    "Oceánie": "Oceania",
    "Bangladéš": "Bangladesh",
    "Japonsko": "Japan",
    "Nippon": "Japan",
    "Lotyšsko": "Latvia",
    "Latvija": "Latvia",
    "Nikaragua": "Nicaragua",
    "Bénin": "Benin",
    "Kambodža": "Cambodia",
    "Prateh Kampuchea": "Cambodia",
    "Pákistán": "Pakistan",
    "Finsko": "Finland",
    "Suomi": "Finland",
    "Việt Nam": "Vietnam",
    "Saúdská Arábie": "Saudi Arabia",
    "Indie": "India",
    "Maledivy": "Maldives",
    "Dhivehi Raajje": "Maldives",
    "Tanzanie": "Tanzania",
    "Indonésie": "Indonesia",
    "Irsko": "Ireland",
    "Gruzie": "Georgia",
    "Sakartvelo": "Georgia",
    "Norsko": "Norway",
    "Norge": "Norway",
    "Kyrgyzstán": "Kyrgyz Republic",
    "Pobřeží slonoviny": "Côte d'Ivoire",
    "Uzbekistán": "Uzbekistan",
    "O'zbekiston": "Uzbekistan",
    "Ekvádor": "Ecuador",
    "Slovinsko": "Slovenia",
    "Slovenija": "Slovenia",
    "Jemen": "Yemen",
    "Al Yaman": "Yemen",
    "Dominikánská republika": "Dominican Republic",
    "República Dominicana": "Dominican Republic",
    "Moldávie": "Moldova",
    "Bahrajn": "Bahrain",
    "Řecko": "Greece",
    "Hellas": "Greece",
    "Misr": "Egypt",
    "Brunej": "Brunei",
    "Island": "Iceland",
    "Ísland": "Iceland",
    "Prathet Thai": "Thailand",
    "Thajsko": "Thailand",
    "Jordánsko": "Jordan",
    "Al Urdun": "Jordan",
    "Hanguk": "South Korea",
    "Jižní Korea": "South Korea",
    "Kostarika": "Costa Rica",
    "Trinidad a Tobago": "Trinidad & Tobago",
    "Severní Makedonie": "North Macedonia",
    "Severna Makedonija": "North Macedonia",
    "Mosambik": "Mozambique",
    "Moçambique": "Mozambique",
    "Jihoafrická republika": "South Africa",
    "Mexiko": "Mexico",
    "México": "Mexico",
    "Maroko": "Morocco",
    "Al Maghrib": "Morocco",
    "Libanon": "Lebanon",
    "Lubnan": "Lebanon",
    "Mongolsko": "Mongolia",
    "Mongol Uls": "Mongolia",
    "Černá Hora": "Montenegro",
    "Crna Gora": "Montenegro",
    "Palestina": "Palestine",
    "Surinam": "Suriname",
    "Srbsko": "Serbia",
    "Srbija": "Serbia",
    "Irák": "Iraq",
    "Al Iraq": "Iraq",
    "Tunisko": "Tunisia",
    "Tounes": "Tunisia",
    "Hongkong": "Hong Kong",
    "Ukrajina": "Ukraine",
    "Ukraina": "Ukraine",
    "Keňa": "Kenya",
    "Bolívie": "Bolivia",
    "Albánie": "Albania",
    "Shqiperia": "Albania",
    "Omán": "Oman",
    "Faerské ostrovy": "Faroe Islands",
    "Føroyar": "Faroe Islands",
    "Malajsie": "Malaysia",
    "Estonsko": "Estonia",
    "Eesti": "Estonia",
    "Dawlat Quatar": "Quatar",
    "Katar": "Quatar",
    "Salvador": "El Salvador",
    "Komory": "Comoros",
    "Lietuva": "Lithuania",
    "Litva": "Lithuania",
    "Taiwan": "Chinese Taipei",
    "Severní Irsko": "Northern Ireland",
    "Cymru": "Wales",
    "Lichtenštejnsko": "Liechtenstein",
    "Kuvajt": "Kuwait",
    "Al Kuwayt": "Kuwait",
    "Sýrie": "Syria",
    "Suriyah": "Syria",
    "Kolumbie": "Colombia",
    "Ázerbájdžán": "Azerbaijan",
    "Azərbaycan": "Azerbaijan",
    "Svatý Tomáš a Princův ostrov": "São Tomé e Príncipe",
    "Kuba": "Cuba",
    "Spojené arabské emiráty": "United Arab Emirates",
    "Kypr": "Cyprus",
    "Alžírsko": "Algeria",
    "Algérie": "Algeria",
    "Hayastan": "Armenia",
    "Arménie": "Armenia",
    "Curacao": "Curaçao",
    "Madagaskar": "Madagascar",
    "Madagasikara": "Madagascar",
    "Kongo": "Congo",
    "RD Congo": "Congo",
    "Democratic Republic of the Congo": "Congo",
    "Svatý Vincenc a Grenadiny": "Saint Vincent and the Grenadines",
    "Ītyōṗṗyā": "Ethiopia",
    "Etiopie": "Ethiopia",
    "Federal Democratic Republic of Ethiopia": "Ethiopia",
    "Srí Lanka": "Sri Lanka",
    "Zambie": "Zambia",
    "Portoriko": "Puerto Rico",
};
